name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '17.5.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: CI=false && npm run build

      - name: Heroku Docker Container Deploy
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: "toxyflog1627@gmail.com"
          api_key: ${{secrets.HEROKU_API_KEY}}
          app_name: "trelo-front"
          dockerfile_path: ""