name: Build

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.5.x'
      - run: npm install
      - run: CI=false && npm run build
      - run: ls -al
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    
    steps:  
    - name: Checkout
      uses: actions/checkout@v2
    - name: Heroku Docker Container Deploy
      uses: jctaveras/heroku-deploy@v2.1.3
      with:
        email: "toxyflog1627@gmail.com"
        api_key: ${{secrets.HEROKU_API_KEY}}
        app_name: "trelo-front"
        dockerfile_path: ""
